server:
  port: ${porta:8761} 

eureka:
  instance:
    hostname: ${hostname:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/